apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: ardpeiris/gateway
        ports:
        - containerPort: 4000
        env:
        - name: AUTH_API
          value: "http://authentication:4001"
        - name: COURSE_API
          value: "http://course:4003"
        - name: LEARNER_API
          value: "http://learner:4002"
        - name: PAYMENT_API
          value: "http://payment:4004"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: ardpeiris/authentication
        ports:
        - containerPort: 4001
        env:
        - name: AUTH_MONGO_URI
          value: "mongodb+srv://admin:admin@ds-assignment.zcgvt27.mongodb.net/user"
        - name: JWT_SECRET
          value: ds-assignment
---
apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
      - name: course
        image: ardpeiris/course
        ports:
        - containerPort: 4002
        env:
        - name: COURSE_MONGO_URI
          value: "mongodb+srv://admin:admin@ds-assignment.zcgvt27.mongodb.net/course"
---
apiVersion: v1
kind: Service
metadata:
  name: course
spec:
  selector:
    app: course
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner
  template:
    metadata:
      labels:
        app: learner
    spec:
      containers:
      - name: learner
        image: ardpeiris/learner
        ports:
        - containerPort: 4003
        env:
        - name: LEARNER_MONGO_URI
          value: "mongodb+srv://admin:admin@ds-assignment.zcgvt27.mongodb.net/learner"
---
apiVersion: v1
kind: Service
metadata:
  name: learner
spec:
  selector:
    app: learner
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: ardpeiris/payment
        ports:
        - containerPort: 4004
        env:
        - name: PAYMENT_MONGO_URI
          value: "mongodb+srv://admin:admin@ds-assignment.zcgvt27.mongodb.net/payment"
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 4004
      targetPort: 4004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ardpeiris/frontend
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer