name: Snyk Scanning

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  snyk-scan:
  
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect and Install Dependencies
        run: |
          cd ${{ inputs.context_path }}

          if [ -f "package.json" ]; then
            echo "Node.js project detected. Installing dependencies with npm."
            npm install
          elif [ -f "requirements.txt" ]; then
            echo "Python project detected. Installing dependencies with pip."
            pip install -r requirements.txt
          elif [ -f "pom.xml" ]; then
            echo "Java project detected. Installing dependencies with Maven."
            mvn install
          else
            echo "Unsupported project type. No dependency installation command found."
            exit 1
          fi

      - name: Set up Snyk
        uses: snyk/actions/setup@master
        with:
          version: 'latest'

      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test (Code + Dependencies Scan)
        run: |
          cd ${{ inputs.context_path }}
          snyk test --all-projects

      - name: Run Snyk Monitoring
        run: |
          cd ${{ inputs.context_path }}
          snyk monitor --all-projects

      - name: Upload Snyk results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-results.sarif
        if: always()